language: ruby
cache: bundler

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.6
  - 2.6.5
  - 2.7.0

gemfile:
  - gemfiles/Gemfile.rails-3-0-stable
  - gemfiles/Gemfile.rails-3-1-stable
  - gemfiles/Gemfile.rails-3-2-stable
  - gemfiles/Gemfile.rails-4-0-stable
  - gemfiles/Gemfile.rails-4-1-stable
  - gemfiles/Gemfile.rails-4-2-stable
  - gemfiles/Gemfile.rails-5-0-stable
  - gemfiles/Gemfile.rails-5-1-stable
  - gemfiles/Gemfile.rails-5-2-stable
  - Gemfile
jobs:
  exclude:
    # Exclude Rails 5 from Ruby < 2.3
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-2-stable
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-2-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-5-2-stable
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    # Exclude Rails 6 from Ruby < 2.5
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.10
      gemfile: Gemfile
    - rvm: 2.2.10
      gemfile: Gemfile
    - rvm: 2.3.8
      gemfile: Gemfile
    - rvm: 2.4.9
      gemfile: Gemfile
    # Exclude Rails 3.0 from Ruby => 2.5
    - rvm: 2.5.6
      gemfile: gemfiles/Gemfile.rails-3-0-stable
    - rvm: 2.6.5
      gemfile: gemfiles/Gemfile.rails-3-0-stable
    #  Exclude Rails 3 and 4 from Ruby 2.7, as they require 
    #   Bunder < 2, and Ruby 2.7 ships with Bundler 2.1.2, and
    #   I can't seem to force it to use an earlier version
    - rvm: 2.7.0
      gemfile: gemfiles/Gemfile.rails-3-0-stable
    - rvm: 2.7.0
      gemfile: gemfiles/Gemfile.rails-3-1-stable
    - rvm: 2.7.0
      gemfile: gemfiles/Gemfile.rails-3-2-stable
    - rvm: 2.7.0
      gemfile: gemfiles/Gemfile.rails-4-0-stable
    - rvm: 2.7.0
      gemfile: gemfiles/Gemfile.rails-4-1-stable
    - rvm: 2.7.0
      gemfile: gemfiles/Gemfile.rails-4-2-stable
  include:
    - name: Documentation
      script: bundle exec jekyll build
      rvm: 2.6.5
      gemfile: Gemfile
      if: branch = master AND type = push
      deploy:
        local_dir: _site
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - hunterae@gmail.com
    on_failure: change
    on_success: never
